#!/bin/sh
# chkconfig: 2345 90 10
# description: Command Scheduler
# processname: crond

### BEGIN INIT INFO
# Provides: crond
# Required-Start: $local_fs $network $syslog $time
# Required-Stop: $local_fs $network $syslog $time
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start/stop crond daemon
### END INIT INFO

# Source function library
. /etc/init.d/functions

# Load environment variables
[ -f /etc/sysconfig/crond ] && . /etc/sysconfig/crond

DAEMON=/usr/sbin/crond
PIDFILE=/var/run/crond.pid

case "$1" in
  start)
    echo -n "Starting crond: "
    daemon "$DAEMON $CRONDARGS"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/crond
    ;;
  stop)
    echo -n "Stopping crond: "
    killproc $DAEMON
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/crond
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  reload)
    echo -n "Reloading crond: "
    killproc $DAEMON -HUP
    echo
    ;;
  status)
    status $DAEMON
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac

exit 0
