#!/bin/bash
# chkconfig: 2345 10 90 
# description: Start and Stop redis
. /etc/profile
REDISPORT=6379
EXEC=/bin/redis-server
CLIEXEC=/bin/redis-cli
PIDFILE=/tmp/redis_${REDISPORT}.pid
CONF="/etc/redis.conf"
case "$1" in
  start)
    if [ -f $PIDFILE ]
    then
        echo "$PIDFILE exists, process is already running or crashed"
    else
        echo "Starting Redis server..."
        $EXEC $CONF
    fi
    ;;
  stop)
    if [ ! -f $PIDFILE ]
    then
        echo "$PIDFILE does not exist, process is not running"
    else
        PID=$(cat $PIDFILE)
        echo "Stopping ..."
        $CLIEXEC -p $REDISPORT shutdown
        while [ -x /proc/${PID} ]
        do
          echo "Waiting for Redis to shutdown ..."
          sleep 1
        done
        echo "Redis stopped"
    fi
    ;;
  restart)
    "$0" stop
    sleep 3
    "$0" start
    ;;
  *)
    echo "Please use start or stop or restart as first argument"
    ;;
esac